- name: Install Satellite
  hosts: localhost
  collections:
  - ansible.posix
  - redhat.satellite_operations
  - redhat.satellite
  - community.general
  vars:

  tasks:
  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Enable a RHSM repository
    rhsm_repository:
      name: 
        - rhel-7-server-rpms
        - rhel-7-server-satellite-6.9-rpms
        - rhel-7-server-satellite-maintenance-6-rpms 
        - rhel-server-rhscl-7-rpms 
        - rhel-7-server-ansible-2.9-rpms
      state: enabled

  - name: Install Satellite RPMs
    ansible.builtin.yum:
      name:
        - satellite
      state: latest


  - name: Allow port 80/tcp
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: Allow port 443/tcp
    ansible.posix.firewalld:
      zone: public
      port: 443/tcp
      permanent: yes
      state: enabled

  - name: Allow port 8000/tcp
    ansible.posix.firewalld:
      zone: public
      port: 8000/tcp
      permanent: yes
      state: enabled

  - name: Allow port 9090/tcp
    ansible.posix.firewalld:
      zone: public
      port: 9090/tcp
      permanent: yes
      state: enabled

  - name: Allow port 5000/tcp
    ansible.posix.firewalld:
      zone: public
      port: 5000/tcp
      permanent: yes
      state: enabled

  - name: Allow port 5647/tcp
    ansible.posix.firewalld:
      zone: public
      port: 5647/tcp
      permanent: yes
      state: enabled

  - name: Allow port 8140/tcp
    ansible.posix.firewalld:
      zone: public
      port: 8140/tcp
      permanent: yes
      state: enabled

  - name: Allow port 53/tcp
    ansible.posix.firewalld:
      zone: public
      port: 53/tcp
      permanent: yes
      state: enabled

  - name: Allow port 53/udp
    ansible.posix.firewalld:
      zone: public
      port: 53/udp
      permanent: yes
      state: enabled

  - name: Allow port 67/udp
    ansible.posix.firewalld:
      zone: public
      port: 67/udp
      permanent: yes
      state: enabled

  - name: Allow port 69/udp
    ansible.posix.firewalld:
      zone: public
      port: 69/udp
      permanent: yes
      state: enabled
