- name: Import and Create Content - Red Hat Enterprise Linux 7 Server
  hosts: localhost
  vars:
    content_view: RHEL
    product: "Red Hat Enterprise Linux Server"
    repo: "Red Hat Enterprise Linux 7 Server (RPMs)"
    repo_variants:
      - releasever: "7Server"
        basearch: "x86_64"
    organization: ACME
  tasks:
    - name: "Enable {{ repo }} repository"
      redhat.satellite.repository_set:
        name: "{{ repo }}"
        product: "{{ product }}"
        repositories: "{{ repo_variants }}"
        organization: "{{ organization }}"
        state: enabled
    
    - name: "Sync {{ repo }} repository"
      redhat.satellite.repository_sync:
        repository: "{{ repo }}"
        product: "{{ product }}"
        organization: "{{ organization }}"
    
    - name: "Create RHEL ContentView"
      redhat.satellite.content_view:
        name: "{{ content_view }}"
        repositories:
          - name: "{{ repo }}"
            product: "{{ product }}"
        organization: "{{ organization }}"
        state: present
    
    - name: "Publish RHEL content view"
      redhat.satellite.content_view_version:
        content_view: "{{ content_view }}"
        organization: "{{ organization }}"
