---
- name: Create a VM using Satellite
  hosts: all
  gather_facts: false

  tasks:
  - name: "Create a host"
    redhat.satellite.host:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      server_url: "https://satellite.entrenchedrealist.com"
      name: "{{ host_name }}"
      state: absent

